.TH "__n3l_forward_data" 3 "Wed Aug 29 2018" "N3 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__n3l_forward_data \- Internal struct to share data between threads\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBref\fP"
.br
.ti -1c
.RI "\fBN3LLayer\fP * \fBlayer\fP"
.br
.ti -1c
.RI "double * \fBresult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal struct to share data between threads\&. 

Initialized from the current layer to the next one\&.
.PP
\fBSee also:\fP
.RS 4
\fB__n3l_forward_get_outputs\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "\fBN3LLayer\fP* __n3l_forward_data::layer"
Current layer 
.SS "uint64_t __n3l_forward_data::ref"
Next layer's neuron reference 
.SS "double* __n3l_forward_data::result"
Sum result while collecting outputs function 

.SH "Author"
.PP 
Generated automatically by Doxygen for N3 Library from the source code\&.
