.TH "src Directory Reference" 3 "Wed Aug 29 2018" "N3 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBn3_act\&.c\fP"
.br
.RI "This file contains activation functions and their primitive\&. "
.ti -1c
.RI "file \fBn3_backward\&.c\fP"
.br
.RI "This file contains functions to backpropagate the error and adjusts the weights\&. "
.ti -1c
.RI "file \fBn3_file\&.c\fP"
.br
.RI "This file contains functions to import and save a network state\&. "
.ti -1c
.RI "file \fBn3_forward\&.c\fP"
.br
.RI "This file contains functions to forward the inputs provided to the outputs\&. "
.ti -1c
.RI "file \fBn3_header\&.h\fP"
.br
.RI "This file contains types, enums and structs definitions\&. "
.ti -1c
.RI "file \fBn3_layer\&.c\fP"
.br
.RI "This file contains functions to work with N3Layer type\&. "
.ti -1c
.RI "file \fBn3_misc\&.c\fP"
.br
.RI "This file contains functions to simplify working with the library\&. "
.ti -1c
.RI "file \fBn3_network\&.c\fP"
.br
.RI "This file contains functions to work with \fBN3LNetwork\fP type\&. "
.ti -1c
.RI "file \fBn3_neuron\&.c\fP"
.br
.RI "This file contains functions to work with N3LNeuron type\&. "
.in -1c
