.TH "_n3l_weight" 3 "Wed Aug 29 2018" "N3 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_n3l_weight
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "uint64_t \fBtarget_ref\fP"
.br
.ti -1c
.RI "struct \fB_n3l_weight\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for N3 Library from the source code\&.
