.TH "_n3l_neuron" 3 "Tue Aug 28 2018" "N3 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_n3l_neuron
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBbias\fP"
.br
.ti -1c
.RI "uint64_t \fBref\fP"
.br
.ti -1c
.RI "double \fBinput\fP"
.br
.ti -1c
.RI "\fBN3LWeight\fP * \fBwhead\fP"
.br
.ti -1c
.RI "double \fBresult\fP"
.br
.ti -1c
.RI "N3LActType \fBact_type\fP"
.br
.ti -1c
.RI "N3LAct \fBact\fP"
.br
.ti -1c
.RI "N3LAct \fBact_prime\fP"
.br
.ti -1c
.RI "struct \fB_n3l_neuron\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fB_n3l_neuron\fP * \fBprev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for N3 Library from the source code\&.
