.TH "src/n3_backward.c" 3 "Sun Sep 2 2018" "N3 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/n3_backward.c \- This file contains functions to backpropagate the error and adjusts the weights\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'n3_header\&.h'\fP
.br
\fC#include 'n3_neuron\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB__n3l_backward_data\fP"
.br
.RI "Internal struct to share data between threads\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fB__n3l_backward_execute\fP (void *arg)"
.br
.RI "Internal function to execute backward propagation from the current layer to the previous one\&. "
.ti -1c
.RI "bool \fBn3l_backward_propagation\fP (\fBN3LNetwork\fP *net)"
.br
.RI "Execute backward propagation on the whole network\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains functions to backpropagate the error and adjusts the weights\&. 


.PP
\fBAuthor:\fP
.RS 4
Davide Francesco Merico 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void * __n3l_backward_execute (void * arg)"

.PP
Internal function to execute backward propagation from the current layer to the previous one\&. Recursive function to execute backpropagation from the current layer to the previous one, only if the layer passed as thread data is not NULL\&. After backpropagate it adjusts the current layer's weights\&.
.PP
\fBParameters:\fP
.RS 4
\fIarg\fP Pointer to an initialized \fB__n3l_backward_data\fP struct 
.RE
.PP
\fBReturns:\fP
.RS 4
No value returned\&.
.RE
.PP
\fBSee also:\fP
.RS 4
n3l_backward_execute, \fB__n3l_backward_data\fP 
.RE
.PP

.SS "bool n3l_backward_propagation (\fBN3LNetwork\fP * net)"

.PP
Execute backward propagation on the whole network\&. Each call to the previous layer from the last layer is executed with concurrents threads\&.
.PP
\fBNote:\fP
.RS 4
The member \fCnet->targets\fP must be initialized before calling this function\&. 
.PP
This function should be called after n3l_forward_execute() 
.RE
.PP
\fBParameters:\fP
.RS 4
\fInet\fP Initialized network 
.RE
.PP
\fBReturns:\fP
.RS 4
TRUE if was correctely executed, otherwise FALSE\&.
.RE
.PP
\fBSee also:\fP
.RS 4
n3l_forward_execute, _n3l_network, \fB__n3l_backward_execute\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for N3 Library from the source code\&.
