.TH "N3LArgs" 3 "Wed Aug 29 2018" "N3 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
N3LArgs
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBbias\fP"
.br
.ti -1c
.RI "uint64_t \fBin_size\fP"
.br
.ti -1c
.RI "uint64_t \fBh_layers\fP"
.br
.ti -1c
.RI "uint64_t * \fBh_size\fP"
.br
.ti -1c
.RI "uint64_t \fBout_size\fP"
.br
.ti -1c
.RI "N3LActType \fBact_in\fP"
.br
.ti -1c
.RI "N3LActType * \fBact_h\fP"
.br
.ti -1c
.RI "N3LActType \fBact_out\fP"
.br
.ti -1c
.RI "void * \fBrand_arg\fP"
.br
.ti -1c
.RI "N3LWeightGenerator \fBrand_weight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for N3 Library from the source code\&.
